In [1]:
import torch

In [25]:
a = torch.Tensor([[4,3], [2,1]])
c = torch.Tensor([[1,2], [3,4]])
b = torch.Tensor([2,1])

In [27]:
torch.concatenate((a,c))

tensor([[4., 3.],
        [2., 1.],
        [1., 2.],
        [3., 4.]])

tensor([[2.],
        [1.]])

In [24]:
torch.diag(b)

tensor([[2., 0.],
        [0., 1.]])

In [12]:
b[b == 2] = 3

In [26]:
b = 0
b

0